### PR TITLE
GitHub actions workflow for sending a package to pypi on release

### PR DESCRIPTION
**Pull request by jpphilips**
Setup File Structure
~Setup pypi project on https://pypi.org/project/big-o-pbeekes/0.0.1/~
Setup workflow

### CODE REVIEW

**Comment by pberkes** [comment]
Hi @jpphilips , thank you for the PR. 

There are several issues with the PR that would need to be fixed before merging
1) A PyPi package for BigO already exists https://pypi.org/project/big-O/
2) The current version is `0.10.2`, as defined in the `setup.py` file
3) My name is misspelled, and the email addresses are fake
4) We can discuss about authorship, but it's either everyone who ever participated, or just me as the original author and main contributor
5) The project URLs are fake
6) The PR changes the permissions of all files, why is that?
6) I would like to have a solution based on the existing `setup.py`, rather than adding a `toml` file and having to maintain both

**Comment by pberkes** [comment]
8. The PR also moved all the tests somewhere else

**Comment by jpphilips** [comment]
Thanks for the feedback
1. Noted. sorry about that
2. fixed
3. fixed
4. Set you as only author
5. fixed
6. I don't know about this. Pls check the recent commit to see if it has been resolved
7. I will delete the toml file yes?
8. fixed

**Comment by pberkes** [comment]
Thank you for the changes. The version of the github action you are using is also very old.
I'll make some changes and re-submit with you as author

**Comment by pberkes** [comment]
@jpphilips I committed a branch called `pypi-workflow` containing the changes you made that are relevant for this task, with you as author. Could you please open a new PR with that branch? Normally I would do it, but I fear you wouldn't get the Hacktoberfest credits

**Comment by jpphilips** [comment]
Thank you. I'm unable to see the branch you created.

**Comment by jpphilips** [comment]
Alright. Thank you but I'm unable to see the branch you created

**Comment by pberkes** [comment]
how about now?

**Comment by pberkes** [comment]
you would need to pull the branch in your fork, then do a PR from there

**Comment by pberkes** [comment]
Closing in favor of #51

**Pull request closed without merging**
